In [3]:
import numpy as np


To create a list of 0-29

In [25]:
## Let's start with a refresh, how to create list of - to 29
a = list(range(30))
a

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

Create a range through Numpy

In [26]:
##this is how we do it in numpyS
b = np.arange(30)
b  

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [6]:
##What is type of object
type(b)

numpy.ndarray

# Stats

In [11]:
##sum of list / NP Array
print(sum(a))
print(b.sum())

435
435


In [13]:
##mean of list / NP Array
print(sum(a)/len(a))
print(b.mean())

14.5
14.5


In [17]:
##max of list / NP Array
print(max(a))
print(b.max())

29
29


# Boolean selections

In [23]:
### With List
### grab value if it is devisible by 2, loop presentation
[x for x in a if x % 2 == 0]

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

In [27]:
### With Numpy
b[b % 2 ==0]   ###numpy representation, with NumPy, you rarely have to code loops, loops are likely to generate errors, Numpy is doing filtering

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [28]:
b % 2 == 0  ##numpy is doing boolean selection, first, it figure out which ones are divisble by 2 and then select those

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [29]:
np.array(list(map(lambda x: x % 2 == 0, b))) ##This is what numpy is doing

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False,  True, False,
        True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False])

In [30]:
## timing of numpy
np2 = np.arange(500000)
%timeit [x for x in np2 if x % 2 == 0]

155 ms ± 2.85 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [31]:
%timeit np2[np2 % 2 ==0]   #Numpy function is much faster

7.24 ms ± 116 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [33]:
a = np.arange(30)
a[(a > 15) | (a <5)]   ## you can use conditions to select items from np array, select items greater than 15 or less than 5

array([ 0,  1,  2,  3,  4, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29])

In [36]:
### data type, to make things more efficient
a.dtype

dtype('int64')

In [37]:
##Qucik stats
a.size

30

In [38]:
a.shape

(30,)

In [39]:
a.argmin()         #location of max

0

In [40]:
a.argmax()   #location of min

29

In [41]:
## numpy allow you to do more sofisticated stuff
np.arange(0,20,2)  #stepping every other 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [42]:
## Other ways to initialize arrway
##https://numpy.org/doc/stable/reference/routines.array-creation.html

np.linspace(1,2,11)   ###break 1 and 2 into 11 numbers, numpy make this super easy

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. ])

In [45]:
#### NaN not a number, when we do operations that doesn't work, it will still run but return not a number
###vs. 0/0
problem = np.array([0])/np.array([0])

<ipython-input-45-2666ba63faed>:3: RuntimeWarning: invalid value encountered in true_divide
  problem = np.array([0])/np.array([0])


In [46]:
problem

array([nan])

In [47]:
problem * 2

array([nan])

In [50]:
##What happens when we have nan in a list
b = np.linspace(0,10,11)
b

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
b[0] = np.nan
b

array([nan,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [53]:
b.min(), b.max(), b.mean()  ## function will return nan because 

(nan, nan, nan)

In [57]:
np.nanmin(b), np.nanmax(b), np.nanmean(b)

(1.0, 10.0, 5.5)

ZeroDivisionError: division by zero