In [2]:
import numpy as np

In [6]:
## multi dimentional arrays, focus here is vectorization, precise and efficient code, do things to aggregate instead of loop, individual

### the concept of array programming
npa =  np.random.randint(0, 10, 5)  ##random integers from 0 to 50, I want 20 of them
npa

array([4, 2, 5, 2, 3])

In [7]:
 ### all values multiple by 2
npa * 2

array([ 8,  4, 10,  4,  6])

In [8]:
### numpy range -9223372036854775808 to 9223372036854775807
(npa ** 6) **6    #negative because we went over max, numpy will always autocast low, so if you deal with large number, make sure you cast

array([                   0,          68719476736, -1748363738790708751,
                68719476736,   150094635296999121])

# Use Functions

In [9]:
##we can define our own function

def transformation(val):
    return ((val *2) -1)

In [10]:
transformation(2)

3

In [11]:
transformation(npa)  #we can use functions on numpy array

array([7, 3, 9, 3, 5])

In [12]:
### create a range of first 25 digits
npc = np.arange(25)
npc

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [13]:
npc2 = npc.reshape([5,5])  #we can reshape vectors, this is really useful when we do image processing
npc2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
np.zeros((5,2))  ##create a 5x2 array of 0

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.zeros(npc2.shape)  ## this is really useful as we can create matrix that similar to shape of items we arleady work with

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
###let's try cube, we see nested arrays
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [49]:
### we can also go into higher dimensions, numpy can apply to any dimension of array, you can scale up
np.zeros((4,4,4,4))

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

      

In [18]:
np.random.seed(10)
npd1 = np.random.randint(1,10,25).reshape(5,5)
npd1

array([[5, 1, 2, 1, 2],
       [9, 1, 9, 7, 5],
       [4, 1, 5, 7, 9],
       [2, 9, 5, 2, 4],
       [7, 6, 4, 7, 2]])

In [19]:
npd2 = np.random.randint(1,10,25).reshape(5,5)
npd2

array([[5, 3, 7, 8, 9],
       [9, 3, 1, 7, 8],
       [9, 2, 8, 2, 5],
       [1, 9, 6, 5, 8],
       [9, 9, 3, 7, 3]])

In [20]:
npd1 * 2

array([[10,  2,  4,  2,  4],
       [18,  2, 18, 14, 10],
       [ 8,  2, 10, 14, 18],
       [ 4, 18, 10,  4,  8],
       [14, 12,  8, 14,  4]])

In [21]:
npd2 < npd1   #we can compare between 2 matrix, think about how many for loop you have to do

array([[False, False, False, False, False],
       [False, False,  True, False, False],
       [False, False, False,  True,  True],
       [ True, False, False, False, False],
       [False, False,  True, False, False]])

In [59]:
((npd2 < npd1).sum())  ### you can easily find how many times condition is true

5

In [62]:
npd2.max(axis=1)   ###max of each row

array([9, 9, 9, 9, 9])

In [63]:
npd2.max(axis=0)   ###max of each row

array([9, 9, 8, 8, 9])

In [64]:
npd2.transpose()  ###very quickly to do transpose

array([[5, 9, 9, 1, 9],
       [3, 3, 2, 9, 9],
       [7, 1, 8, 6, 3],
       [8, 7, 2, 5, 7],
       [9, 8, 5, 8, 3]])

In [65]:
npd2.T    ##another shortcut

array([[5, 9, 9, 1, 9],
       [3, 3, 2, 9, 9],
       [7, 1, 8, 6, 3],
       [8, 7, 2, 5, 7],
       [9, 8, 5, 8, 3]])

In [67]:
npd2.transpose() == npd2.T

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [68]:
npd3 = npd2.flatten()   ## you can put multi dimention to single dimension
npd3

array([5, 3, 7, 8, 9, 9, 3, 1, 7, 8, 9, 2, 8, 2, 5, 1, 9, 6, 5, 8, 9, 9,
       3, 7, 3])

In [69]:
npd2.cumsum()  ### cumulative sum

array([  5,   8,  15,  23,  32,  41,  44,  45,  52,  60,  69,  71,  79,
        81,  86,  87,  96, 102, 107, 115, 124, 133, 136, 143, 146],
      dtype=int32)

In [70]:
npd2.cumprod()   ##cumulative product 

array([          5,          15,         105,         840,        7560,
             68040,      204120,      204120,     1428840,    11430720,
         102876480,   205752960,  1646023680, -1002919936,  -719632384,
        -719632384,  2113243136,  -205443072, -1027215360,   372211712,
        -945061888,    84377600,   253132800,  1771929600,  1020821504],
      dtype=int32)

In [ ]:
##### THere is no need to memorize functions, it is a concept on how this is different from loop