In [1]:
import numpy as np

In [2]:
box = np.random.randint(1,99,16).reshape(4,4)
box

array([[70, 22, 73, 69],
       [49, 96,  6,  6],
       [93, 50,  5, 40],
       [68, 25, 31, 76]])

In [3]:
### define reverse order
order = np.array([3,2,1,0])

In [7]:
## reverse all rows
box[order]

array([[68, 25, 31, 76],
       [93, 50,  5, 40],
       [49, 96,  6,  6],
       [70, 22, 73, 69]])

In [8]:
## reverse all columns
box[:, order]

array([[69, 73, 22, 70],
       [ 6,  6, 96, 49],
       [40,  5, 50, 93],
       [76, 31, 25, 68]])

Sort vs. Argsort

In [6]:
p = np.array([9, 3, 1, 7, 4, 3, 6])

In [7]:
##sort the array
np.sort(p)

array([1, 3, 3, 4, 6, 7, 9])

In [8]:
##Reverse
np.sort(p)[::-1]

array([9, 7, 6, 4, 3, 3, 1])

In [9]:
###argsort display position of sorted array assuming sorted
##e.g., the first item should be 1, which is in index 2, etc.
p = np.array([9, 3, 1, 7, 4, 3, 6])
np.argsort(p)

array([2, 1, 5, 4, 6, 3, 0])

In [27]:
box

array([[70, 22, 73, 69],
       [49, 96,  6,  6],
       [93, 50,  5, 40],
       [68, 25, 31, 76]])

In [10]:
##sort by second column
##because we are shifting rows, so we provide index for box, to box

box[box[:,1].argsort()]

NameError: name 'box' is not defined

In [29]:
## sort by second row
## because we are shifting in columns, so we have to have colon first, then have order of rows

box[:,box[1].argsort()]

array([[73, 69, 70, 22],
       [ 6,  6, 49, 96],
       [ 5, 40, 93, 50],
       [31, 76, 68, 25]])

In [34]:
np.sort(box, axis = 0)

array([[49, 22,  5,  6],
       [68, 25,  6, 40],
       [70, 50, 31, 69],
       [93, 96, 73, 76]])

In [33]:
box

array([[70, 22, 73, 69],
       [49, 96,  6,  6],
       [93, 50,  5, 40],
       [68, 25, 31, 76]])