In [2]:
## one of the most important thing is to slice / combine data, do that in Numpy
import numpy as np

In [4]:

## Create an array of 12 eelements
ar = np.arange(12)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
ar[5:] ####skip to 5th item

array([ 5,  6,  7,  8,  9, 10, 11])

In [12]:
ar[:5]  ####select the first 5 items

array([0, 1, 2, 3, 4])

In [14]:
ar[2:8:2]   #### 2 to 8 in steps of 2

array([2, 4, 6])

In [15]:
ar[:-1]  ### grab everything until the last

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
ar[:-5]  ### grab everything until the last 5

array([0, 1, 2, 3, 4, 5, 6])

In [17]:
ar[::-1]   ###backward in step of 1

array([11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [20]:
ar[-1:-8:-2] ###backward in step of 2

array([11,  9,  7,  5])

In [6]:
## set a seed so we get same randomized items
np.random.seed(10)
###let's try 2 dimentional, very important to identify which dimension you are working with
ar2 = np.random.randint(12, size=12).reshape((3,4))
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [23]:
ar2[:,1:3]    ###grabbing everything from column 2 to column 3, first 

array([[4, 0],
       [9, 0],
       [8, 9]])

In [25]:
#####How do we grab last 2 rows?
## use 2 set of colons, first one is number of rows, second one is number of columns
ar2[1:3, :]

array([[11,  9,  0,  1],
       [10,  8,  9,  0]])

In [26]:
ar2[::2, ::2]    ##What will this show us, step of 2

array([[ 9,  0],
       [10,  9]])

In [27]:
ar2[1:3:2, 1:4:2]   ###how do we grab the other numbers, why 4 instead of 3?

array([[9, 1]])

In [29]:
###lets combine them
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [30]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [31]:
ar2.flatten()

array([ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0])

In [32]:
np.vstack([ar, ar2.flatten()]) ### we put then together

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0]])

In [33]:
ar.reshape((3,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [34]:
np.vstack((ar.reshape(3,4), ar2))  ###stacking vertically

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [38]:
np.hstack((ar, ar2.flatten(), ar))    ##everything linked together with hstack

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  9,  4,  0,  1, 11,
        9,  0,  1, 10,  8,  9,  0,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9,
       10, 11])

In [41]:
np.hstack((ar.reshape(3,4), ar2))    ###for h stack, we put the second matrix on the right

array([[ 0,  1,  2,  3,  9,  4,  0,  1],
       [ 4,  5,  6,  7, 11,  9,  0,  1],
       [ 8,  9, 10, 11, 10,  8,  9,  0]])

In [48]:
#### we can also stack with function concatenate

np.concatenate((ar,ar2.flatten()))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  9,  4,  0,  1, 11,
        9,  0,  1, 10,  8,  9,  0])

In [52]:
np.concatenate(([ar],[ar2.flatten()]), axis =0)   ####for one dimension, need to recast the array because to ensure system intepret it property

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [ 9,  4,  0,  1, 11,  9,  0,  1, 10,  8,  9,  0]])

In [53]:
ar2

array([[ 9,  4,  0,  1],
       [11,  9,  0,  1],
       [10,  8,  9,  0]])

In [54]:
np.hsplit(ar2,2)     #split into 2 

[array([[ 9,  4],
        [11,  9],
        [10,  8]]), array([[0, 1],
        [0, 1],
        [9, 0]])]

In [55]:
np.hsplit(ar2,4)     #split into 4

[array([[ 9],
        [11],
        [10]]), array([[4],
        [9],
        [8]]), array([[0],
        [0],
        [9]]), array([[1],
        [1],
        [0]])]

In [56]:
np.hsplit(ar2,3)  #### doesn't work because of the dimension is not divisible

ValueError: array split does not result in an equal division

In [61]:
 v1, v2, v3 = np.vsplit(ar2,3)  #### doesn't work because of the dimension is not divisible

In [58]:
## array transformation can be complicated and confusing and easily generate errors, we can do any split, make sure you

In [59]:
ar2.reshape((4,3))

array([[ 9,  4,  0],
       [ 1, 11,  9],
       [ 0,  1, 10],
       [ 8,  9,  0]])

In [62]:
v1.shape

(1, 4)