In [1]:
###playing card simulation

import numpy as np

In [2]:
deck = np.arange(52)
deck

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51])

In [3]:
deck_suite = deck % 4
deck_suite

array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1,
       2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3,
       0, 1, 2, 3, 0, 1, 2, 3])

In [4]:
deck_num = deck % 13
deck_num = deck_num+1
deck_num

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13,  1,  2,  3,  4,
        5,  6,  7,  8,  9, 10, 11, 12, 13,  1,  2,  3,  4,  5,  6,  7,  8,
        9, 10, 11, 12, 13,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12,
       13])

In [5]:
wholedeck = np.vstack((deck_suite, deck_num))   ##combine suite and number
wholedeck = wholedeck.T   ## transform to make each small array as 1 card
wholedeck

array([[ 0,  1],
       [ 1,  2],
       [ 2,  3],
       [ 3,  4],
       [ 0,  5],
       [ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 0,  9],
       [ 1, 10],
       [ 2, 11],
       [ 3, 12],
       [ 0, 13],
       [ 1,  1],
       [ 2,  2],
       [ 3,  3],
       [ 0,  4],
       [ 1,  5],
       [ 2,  6],
       [ 3,  7],
       [ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 0, 12],
       [ 1, 13],
       [ 2,  1],
       [ 3,  2],
       [ 0,  3],
       [ 1,  4],
       [ 2,  5],
       [ 3,  6],
       [ 0,  7],
       [ 1,  8],
       [ 2,  9],
       [ 3, 10],
       [ 0, 11],
       [ 1, 12],
       [ 2, 13],
       [ 3,  1],
       [ 0,  2],
       [ 1,  3],
       [ 2,  4],
       [ 3,  5],
       [ 0,  6],
       [ 1,  7],
       [ 2,  8],
       [ 3,  9],
       [ 0, 10],
       [ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [9]:
np.random.shuffle(wholedeck)   #shuffle the deck
wholedeck

array([[ 2,  7],
       [ 2,  9],
       [ 1,  4],
       [ 1, 10],
       [ 2,  5],
       [ 0, 12],
       [ 0,  4],
       [ 0, 11],
       [ 3,  5],
       [ 1,  6],
       [ 3,  2],
       [ 0,  1],
       [ 3, 13],
       [ 2,  3],
       [ 2,  1],
       [ 2, 10],
       [ 3,  3],
       [ 1, 12],
       [ 1,  3],
       [ 0, 13],
       [ 3,  9],
       [ 3,  6],
       [ 0,  7],
       [ 2, 11],
       [ 0,  2],
       [ 0,  9],
       [ 2,  8],
       [ 0,  3],
       [ 1, 11],
       [ 1, 13],
       [ 1,  5],
       [ 3, 12],
       [ 3,  8],
       [ 1,  9],
       [ 3,  4],
       [ 3, 10],
       [ 1,  1],
       [ 0,  8],
       [ 1,  8],
       [ 0,  6],
       [ 2, 12],
       [ 2,  4],
       [ 0, 10],
       [ 1,  2],
       [ 0,  5],
       [ 3,  1],
       [ 2,  6],
       [ 1,  7],
       [ 3, 11],
       [ 2, 13],
       [ 2,  2],
       [ 3,  7]])

In [ ]:
wholedeck

In [10]:
##while technically, we only need to work with suite, but let's try to use the whole deck and do maniputation
sample = wholedeck[0:3, 0:1]    #select the suite of the first 3 card
sample

array([[2],
       [2],
       [1]])

In [11]:
#### flatten the result
sample = sample.flatten()
sample

array([2, 2, 1])

In [12]:
#### Check all of them are equal to first item
sample == sample[0]

array([ True,  True, False])

In [13]:
### check of all true
sample.shape[0] == (sample == sample[0]).sum()   #check to see if statement is true

False

In [14]:
def experiment():
    deck = np.arange(52)   ####create deck 
    deck_suite = deck % 4
    deck_num = deck % 13
    wholedeck = np.vstack((deck_suite, deck_num)) 
    wholedeck = wholedeck.T 
    np.random.shuffle(wholedeck)   ####shuffle deck 
    sample = wholedeck[0:3, 0:1]    ####sample deck 
    sample = sample.flatten()
    return sample.shape[0] == (sample == sample[0]).sum()  #return if experiment result result in 3 suites are the same

In [27]:
experiment()    #we can run experiment

False

In [28]:
##### Let's run experiment 1,000,000 times
result =[]
for i in range(0,1000000):
    result.append(experiment())
result_a = np.asarray(result)
result_a

array([False, False, False, ..., False, False, False])

In [29]:
####probably of true
result_a.sum() / result_a.shape[0]

0.051821