## Lecture 2 In Class Exercise

# 1. Generating Random Data and Filtering That Data


In [2]:
import numpy as np
np.random.seed(25)
ar = np.random.randn(1000)

**1.** Multiply all element in AR by 100, display the first 3 elements of ar

In [4]:
print(ar[:3])

[ 0.22827309  1.0268903  -0.83958485]


In [11]:
ar_m_10 = ar*100
print(ar_m_10[:3])

[ 22.82730897 102.68903032 -83.9584849 ]


**2.** Now convert that matrix into a matrix of 8-bit integers. Display first 3 elements

In [13]:
ar_8bit = ar_m_10.astype("int8")
print(ar_8bit[:3])

[ 22 102 -83]


*the first 3 values should be*

```
 22,  102,  -83,
```


**3.** Reshape the array into a set of five columns with 200 rows. Replace the original `ar` array with this new matrix.

In [14]:
ar_8bit.shape

(1000,)

In [17]:
ar = ar_8bit.reshape((200,5))

**4.** Now that `ar` is a matrix, let's get the maximum and minimum values from the matrix both row wise and column wise. Be sure to remember how many total values you should be outputting - one for every row, then one for each column.

In [22]:
ar[0]

array([ 22, 102, -83, -59, -95], dtype=int8)

In [24]:
ar_max_rowwise = ar.max(axis=1)
ar_max_colwise = ar.max(axis=0)
ar_min_rowwise = ar.min(axis=1)
ar_min_colwise = ar.min(axis=0)
print("Row-wise max:")
print(ar_max_rowwise)
print("************************************************************")

print("Col-wise max:")
print(ar_max_colwise)
print("************************************************************")

print("Row-wise min:")
print(ar_min_rowwise)
print("************************************************************")

print("Col-wise min:")
print(ar_min_colwise)

Row-wise max:
[102  86 123 120  99  59  73  63  68  10 117 118  94  57 112  49 119 104
 121  19 102  56 122  17  52  20  54 101  43 -16 112  93  64  59  62  92
  63 101  90 120 111  97  64  40  98 106  96  80  71  59  73  24  57  68
  65 120 117  94 102  28   2  93  66  58 111  83 126  17 111 111  46  70
 121 124  89  98  43  98 106  94 100  78  78  45  71  53   6  86  57 119
 125  37  74  72 105  61 116  80 123  41 117  69  71 110 105  91  33 111
 125 114 121  44 124 116  28  89  -1  67 124 117 126  45  93 106 100  97
 113  64 112  74 118  82 103   1  57 123  50 126 119  24   1 119  80 109
 126  85 110  73 115  52 115  62  54  46 102 107 106  68  79  98  98  78
  68  58  88  86  52  93  75  81 126 104  94  -9 123 118  65 121  79  18
  22  81  48 108 119 116 118  98 121  36 125 -30  87  11  18 114  93  95
  -2 127]
************************************************************
Col-wise max:
[123 125 126 126 127]
************************************************************
Row-wise min:
[

**5.** Now that we have gotten the minimum and maximum values for the columns, get the mean of the entire matrix. (This should be a specific value.)

In [25]:
ar_mean = ar.mean()
print("ar_mean:", ar_mean)

ar_mean: -0.791


**6.** What is the total number of values that are less than the mean?

In [26]:
num_lt_mean = len(ar[ar < ar_mean])
print("Total number of values less than the mean:", num_lt_mean)

Total number of values less than the mean: 494


**7.** What is the total number of values in *each row* that are greater than this mean value? (Remember, if we are doing a row-oriented comparison, how many numbers should be in our output array?)

In [32]:
def my_func(row):
    return len(row[row > ar_mean])
filtered_arr = np.apply_along_axis(my_func, 1, ar)
# num_gt_mean_byrow = np.apply_along_axis(len, 1, ar[ar > ar_mean])
filtered_arr

array([2, 2, 2, 2, 3, 2, 4, 4, 4, 1, 2, 2, 3, 4, 4, 1, 2, 2, 3, 1, 5, 3,
       3, 2, 2, 2, 2, 2, 2, 0, 3, 2, 3, 1, 4, 2, 1, 2, 3, 3, 2, 3, 3, 1,
       2, 1, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 4, 3, 2, 2, 1, 5, 2, 4, 3, 3,
       3, 1, 2, 4, 1, 4, 4, 3, 3, 1, 3, 4, 3, 4, 2, 3, 3, 4, 2, 2, 1, 3,
       1, 2, 4, 1, 1, 4, 2, 4, 2, 2, 2, 1, 2, 5, 4, 3, 4, 5, 2, 4, 4, 2,
       4, 3, 3, 4, 1, 2, 0, 3, 2, 4, 3, 3, 3, 2, 4, 2, 3, 1, 2, 4, 4, 2,
       4, 1, 1, 3, 4, 2, 3, 1, 1, 2, 2, 4, 2, 2, 5, 2, 4, 1, 2, 3, 2, 2,
       4, 1, 3, 1, 4, 2, 2, 3, 1, 2, 3, 3, 3, 4, 3, 2, 3, 3, 3, 0, 3, 3,
       1, 2, 3, 1, 1, 4, 3, 5, 3, 4, 2, 1, 3, 2, 2, 0, 1, 1, 3, 3, 3, 3,
       0, 5])

**8.** How many zeros are in the matrix that we have?

In [38]:
len(ar[ar == 0])

8

**9.** Lastly, sum all the values that are either greater than 100 or are less than 5

In [43]:
ar[ar > 100].sum() + ar[ar < 5].sum()

-20589

# 2. More NumPy Basics

Using NumPy to do the following and display result for each step
1. Create a dataset of 50 random integers ranging from 0 and 100.
2. Reshape the data to be 10x5.
3. Create a dataset of 50 numbers between 0 and 100 using linspace()
4. Reshape the data to be 10x5.
5. Use vstack to stack the data for the two arrays call it "vertstk"
6. Use hstack to stack the data for the two arrays call it "hozstk"
7. for each array divide each element by 2:<br>
    a. Use a functional approach (such as map or filter) for hozstk and a vectorized approach for vertstk<br>
    b. for an extra challenge replace all values greater than 25 with 25
8. get column and row means for hozstk and vertstk

In [59]:
np.random.seed(100)
data = np.random.randint(low=0, high=101, size=50).reshape((10,5))

In [60]:
data

array([[  8,  24,  67,  87,  79],
       [ 48,  10,  94,  52,  98],
       [ 53,  66,  98,  14,  34],
       [ 24,  15, 100,  60,  58],
       [ 16,   9,  93,  86,   2],
       [ 27,   4,  31,   1,  13],
       [ 83, 100,   4,  91,  59],
       [ 67,   7,  49,  47,  65],
       [ 61,  14,  55,  71,  80],
       [  2,  94,  19,  98,  63]])

In [64]:
data_linspace = np.linspace(start=0, stop=100, num=50).reshape((10,5))

In [73]:
data_linspace

array([[  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531],
       [ 10.20408163,  12.24489796,  14.28571429,  16.32653061,
         18.36734694],
       [ 20.40816327,  22.44897959,  24.48979592,  26.53061224,
         28.57142857],
       [ 30.6122449 ,  32.65306122,  34.69387755,  36.73469388,
         38.7755102 ],
       [ 40.81632653,  42.85714286,  44.89795918,  46.93877551,
         48.97959184],
       [ 51.02040816,  53.06122449,  55.10204082,  57.14285714,
         59.18367347],
       [ 61.2244898 ,  63.26530612,  65.30612245,  67.34693878,
         69.3877551 ],
       [ 71.42857143,  73.46938776,  75.51020408,  77.55102041,
         79.59183673],
       [ 81.63265306,  83.67346939,  85.71428571,  87.75510204,
         89.79591837],
       [ 91.83673469,  93.87755102,  95.91836735,  97.95918367,
        100.        ]])

In [74]:
vertstk = np.vstack((data, data_linspace))
vertstk

array([[  8.        ,  24.        ,  67.        ,  87.        ,
         79.        ],
       [ 48.        ,  10.        ,  94.        ,  52.        ,
         98.        ],
       [ 53.        ,  66.        ,  98.        ,  14.        ,
         34.        ],
       [ 24.        ,  15.        , 100.        ,  60.        ,
         58.        ],
       [ 16.        ,   9.        ,  93.        ,  86.        ,
          2.        ],
       [ 27.        ,   4.        ,  31.        ,   1.        ,
         13.        ],
       [ 83.        , 100.        ,   4.        ,  91.        ,
         59.        ],
       [ 67.        ,   7.        ,  49.        ,  47.        ,
         65.        ],
       [ 61.        ,  14.        ,  55.        ,  71.        ,
         80.        ],
       [  2.        ,  94.        ,  19.        ,  98.        ,
         63.        ],
       [  0.        ,   2.04081633,   4.08163265,   6.12244898,
          8.16326531],
       [ 10.20408163,  12.24489796,  14.285

In [75]:
hozstk = np.hstack((data, data_linspace))
hozstk

array([[  8.        ,  24.        ,  67.        ,  87.        ,
         79.        ,   0.        ,   2.04081633,   4.08163265,
          6.12244898,   8.16326531],
       [ 48.        ,  10.        ,  94.        ,  52.        ,
         98.        ,  10.20408163,  12.24489796,  14.28571429,
         16.32653061,  18.36734694],
       [ 53.        ,  66.        ,  98.        ,  14.        ,
         34.        ,  20.40816327,  22.44897959,  24.48979592,
         26.53061224,  28.57142857],
       [ 24.        ,  15.        , 100.        ,  60.        ,
         58.        ,  30.6122449 ,  32.65306122,  34.69387755,
         36.73469388,  38.7755102 ],
       [ 16.        ,   9.        ,  93.        ,  86.        ,
          2.        ,  40.81632653,  42.85714286,  44.89795918,
         46.93877551,  48.97959184],
       [ 27.        ,   4.        ,  31.        ,   1.        ,
         13.        ,  51.02040816,  53.06122449,  55.10204082,
         57.14285714,  59.18367347],
       [ 8

In [77]:
vert_div2 = vertstk/2
vert_div2

array([[ 4.        , 12.        , 33.5       , 43.5       , 39.5       ],
       [24.        ,  5.        , 47.        , 26.        , 49.        ],
       [26.5       , 33.        , 49.        ,  7.        , 17.        ],
       [12.        ,  7.5       , 50.        , 30.        , 29.        ],
       [ 8.        ,  4.5       , 46.5       , 43.        ,  1.        ],
       [13.5       ,  2.        , 15.5       ,  0.5       ,  6.5       ],
       [41.5       , 50.        ,  2.        , 45.5       , 29.5       ],
       [33.5       ,  3.5       , 24.5       , 23.5       , 32.5       ],
       [30.5       ,  7.        , 27.5       , 35.5       , 40.        ],
       [ 1.        , 47.        ,  9.5       , 49.        , 31.5       ],
       [ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265],
       [ 5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347],
       [10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429],
       [15.30612245, 16.32653061, 17.3

In [81]:
hoz_div2 = np.array(list(map(lambda x: x / 2, hozstk)))
hoz_div2

array([[ 4.        , 12.        , 33.5       , 43.5       , 39.5       ,
         0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265],
       [24.        ,  5.        , 47.        , 26.        , 49.        ,
         5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347],
       [26.5       , 33.        , 49.        ,  7.        , 17.        ,
        10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429],
       [12.        ,  7.5       , 50.        , 30.        , 29.        ,
        15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ],
       [ 8.        ,  4.5       , 46.5       , 43.        ,  1.        ,
        20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592],
       [13.5       ,  2.        , 15.5       ,  0.5       ,  6.5       ,
        25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673],
       [41.5       , 50.        ,  2.        , 45.5       , 29.5       ,
        30.6122449 , 31.63265306, 32.65306122

In [84]:
hoz_rowmeans = hoz_div2.mean(axis=1)
hoz_colmeans = hoz_div2.mean(axis=0)
vert_rowmeans = vert_div2.mean(axis=1)
vert_colmeans = vert_div2.mean(axis=0)

print("Row-wise mean for hozstk:")
print(hoz_rowmeans)
print("************************************************************")

print("Col-wise mean for hozstk:")
print(hoz_colmeans)
print("************************************************************")

print("Row-wise mean for vertstk:")
print(vert_rowmeans)
print("************************************************************")

print("Col-wise mean for vertstk:")
print(vert_colmeans)

Row-wise mean for hozstk:
[14.27040816 18.67142857 19.37244898 21.52346939 21.5244898  17.5755102
 33.17653061 30.62755102 35.47857143 37.77959184]
************************************************************
Col-wise mean for hozstk:
[19.45       17.15       30.5        30.35       27.55       22.95918367
 23.97959184 25.         26.02040816 27.04081633]
************************************************************
Row-wise mean for vertstk:
[26.5        30.2        26.5        25.7        20.6         7.6
 33.7        23.5        28.1        27.6         2.04081633  7.14285714
 12.24489796 17.34693878 22.44897959 27.55102041 32.65306122 37.75510204
 42.85714286 47.95918367]
************************************************************
Col-wise mean for vertstk:
[21.20459184 20.56479592 27.75       28.18520408 27.29540816]
